name: "reactive-rdb-app-kt-plugin"
description: Configures database connection to a relational database through supported reactive drivers (MariaDB, MySQL, PostgreSQL) and optionally migration during application startup on a reactive project
types:
  - app
tags:
  - "reactive"
  - "relational-database"
  - "migration"
  - "flyway"
  - "liquibase"
inputs:
  - label: "Which database would you like to use?"
    type: text
    name: "dbms"
    default: "PostgreSQL"
    items:
      - "MariaDB"
      - "MySQL"
      - "PostgreSQL"

  - label: "Which migration tool would you like to use with this datasource?"
    type: "text"
    name: "migration_tool"
    default: "None"
    items:
      - "Flyway"
      - "Liquibase"
      - "None"
